#!/bin/sh

RSS_DATA=""
POST_DATA=""
FILE_DATA=""
for file in fragments/*.html; do
	# Get the Post Number
	POST=$(basename $file)
	POST_N=${POST%\.*}

	# Format the RSS file to <item><title><link><description></item>
	#\n\t\t<pubdate>$(date +"%a, %d %b %Y %I:%M:%S %:::z")</pubdate>
	INNER_RSS=$(sed 's/h2/title/g' fragments/${POST} | sed 's/^\([^<].*\)$/\t\t<description>\1<\/description>/g')
	INNER_RSS="\t\t<item>\n${INNER_RSS}\n\t\t<link>https://TerminalCursor.github.io/posts#post-${POST_N}</link>\n\t\t</item>"
	RSS_DATA="${INNER_RSS}\n${RSS_DATA}"

	# Make a master post file
	FILE_DATA=$(cat $file)
	FILE_DATA=$(printf "${FILE_DATA}" | sed "s/<h2>/<h2><a href=\"https:\/\/TerminalCursor.github.io\/posts#post-${POST_N}\">/")
	FILE_DATA=$(printf "${FILE_DATA}" | sed "s/<\/h2>/<\/a><\/h2>/")
	POST_DATA="<div class=\"box layer3\" id=\"post-${POST_N}\">\n${FILE_DATA}\n</div>\n${POST_DATA}"
done

# Write the RSS feed
SUBSTR="<!-- RSS DATA HERE -->"
printf "${RSS_DATA}\n" > temp
sed -e "/$SUBSTR/r temp" -e "/$SUBSTR/d" skeletons/rss > rss.xml

# Write the Post file
SUBSTR="<!-- POST DATA HERE -->"
printf "${POST_DATA}\n" > temp
sed -e "/$SUBSTR/r temp" -e "/$SUBSTR/d" skeletons/posts > posts/index.html

# Write links to link file
SUBSTR="<!-- LINKS -->"
LINKS=""
for file in links/*.lnk; do
	LINKS="${LINKS}\n<div class=\"box layer2\">\n$(cat $file)\n</div>"
done
printf "${LINKS}" > temp
sed -e "/$SUBSTR/r temp" -e "/$SUBSTR/d" skeletons/links > links/index.html
rm temp
